### ISSUE TITLE
eg25-autorestart: timer starts only once, then dies

### ISSUE THREAD

**Issue by SantX27** [kescherCode/kescher-archpp#4]
Hi, first of all thank you for your repo, birdie and touchpad-emulator are really good and having them already packaged is very cool. However, I can't for the life of me get eg25-autorestart to work properly. I've installed the package, then I ran **systemctl enable eg25-autorestart.timer** (I've also tried enabling the service, to no avail since it's made for being used by the timer), then I simply rebooted the Pinephone, assuming it would just keep running every 5 minutes to check if the modem is still online. But this doesn't happen, instead the timer triggers only once (usually during boot), and then I assume that what happens is that the timer deactivates itself, until I run **systemctl start eg25-autorestart.timer** manually, which followes the same fate as the first one. Here's the output of **systemctl status eg25-autoreboot.timer**:

> 
> ○ eg25-autorestart.timer - Quectel EG25 autorestart timer
>      Loaded: loaded (/etc/systemd/system/eg25-autorestart.timer; enabled; vendor preset: disabled)
>      Active: inactive (dead) since Tue 2021-08-31 19:43:24 CEST; 4h 36min ago
>     Trigger: n/a
>    Triggers: ● eg25-autorestart.service
> 
> ago 31 19:43:23 miria systemd[1]: Started Quectel EG25 autorestart timer.
> ago 31 19:43:24 miria systemd[1]: eg25-autorestart.timer: Deactivated successfully.
> ago 31 19:43:24 miria systemd[1]: Stopped Quectel EG25 autorestart timer.

And **systemctl status eg25-autorestart.service**:

> ○ eg25-autorestart.service - Quectel EG25 autorestart
>      Loaded: loaded (/usr/lib/systemd/system/eg25-autorestart.service; static)
>      Active: inactive (dead) since Tue 2021-08-31 19:43:34 CEST; 4h 56min ago
> TriggeredBy: ○ eg25-autorestart.timer
>     Process: 3457 ExecStart=/usr/lib/eg25-autorestart/eg25-autorestart.sh (code=exited, status=0/SUCCESS)
>    Main PID: 3457 (code=exited, status=0/SUCCESS)
>         CPU: 250ms
> 
> ago 31 19:43:23 miria systemd[1]: Starting Quectel EG25 autorestart...
> ago 31 19:43:34 miria systemd[1]: eg25-autorestart.service: Deactivated successfully.
> ago 31 19:43:34 miria systemd[1]: Finished Quectel EG25 autorestart.
> 

I'm kinda sure this is some sorta of misconfiguration on my side since I'm the only one who has this problem, but I don't understand why would it deactivate, since the service and the timer were not modified.

**Comment by kescherCode** [comment]
First off, "Deactivated successfully" means the script executed successfully. It's NOT an error message, and it doesn't mean anything was deactivated. systemd prints this when what was defined in `ExecStart` exits with error code 0.
I suggest running `systemctl enable --now eg25-autorestart.timer`.

Second: What is installed on your PinePhone? If you're using e.g. Plasma Mobile on Manjaro, [it seems eg25-autorestart.sh needs some changes](https://github.com/kescherCode/kescher-archpp/pull/2#issuecomment-907541935), but I have no clue what `ofono` would need in order for the script to work. If you're using ModemManager, that would be an interesting bug with the existing code to figure out though.

**Comment by SantX27** [comment]
Oh, I've forced my mind into reading everything as an error, sorry. Also I have omitted that I'm running Phosh on [Danctnix's Arch](https://github.com/dreemurrs-embedded/Pine64-Arch) and I have no trace of oFono on my system.
I have run `systemctl enable --now eg25-autorestart.timer` but running `systemctl status eg25-autorestart.timer` after it gives me the same status:

> ○ eg25-autorestart.timer - Quectel EG25 autorestart timer
> Loaded: loaded (/etc/systemd/system/eg25-autorestart.timer; enabled; vendor preset: disabled)
> Active: inactive (dead) since Wed 2021-09-01 10:13:39 CEST; 3s ago
> Trigger: n/a
> Triggers: ● eg25-autorestart.service
> set 01 10:13:39 miria systemd[1]: Started Quectel EG25 autorestart timer.
> set 01 10:13:39 miria systemd[1]: eg25-autorestart.timer: Deactivated successfully.
> set 01 10:13:39 miria systemd[1]: Stopped Quectel EG25 autorestart timer.

For sake of completeness, here's the `systemctl cat` of the timer and the service:

> ## /etc/systemd/system/eg25-autorestart.timer
> [Unit]
> Description=Quectel EG25 autorestart timer
> Requires=eg25-manager.service
> After=eg25-manager.service
> [Timer]
> OnCalendar=*:0/5
> Persistent=true
> [Install]
> WantedBy=timers.target

> ## /usr/lib/systemd/system/eg25-autorestart.service
> [Unit]
> Description=Quectel EG25 autorestart
> [Service]
> Type=oneshot
> ExecStart=/usr/lib/eg25-autorestart/eg25-autorestart.sh

**Comment by kescherCode** [comment]
Hm... I think I should remove the "Requires" and "After" lines from the timer and instead do a condition check on eg25-autorestart.service in the eg25-autorestart unit file. I think the timer might be triggering too early due to being a persistent timer.

**Comment by kescherCode** [comment]
Indeed, my PinePhone does this on boot sometimes. I'll test my changes and push a commit and an updated package right away.

**Comment by kescherCode** [comment]
eg25-autorestart-0.4-1 has been released on the custom repo.

**Comment by SantX27** [comment]
Testing it right now, seems good:

> ● eg25-autorestart.timer - Quectel EG25 autorestart timer
> Loaded: loaded (/etc/systemd/system/eg25-autorestart.timer; enabled; vendor preset: disabled)
> Active: active (waiting) since Wed 2021-09-01 12:06:15 CEST; 1min 16s ago
> Trigger: Wed 2021-09-01 12:10:00 CEST; 2min 28s left
> Triggers: ● eg25-autorestart.service
> set 01 12:06:15 miria systemd[1]: Started Quectel EG25 autorestart timer.

Edit: I spoke too soon:

> ○ eg25-autorestart.timer - Quectel EG25 autorestart timer
> Loaded: loaded (/etc/systemd/system/eg25-autorestart.timer; enabled; vendor preset: disabled)
> Active: inactive (dead) since Wed 2021-09-01 12:10:01 CEST; 1min 7s ago
> Trigger: n/a
> Triggers: ● eg25-autorestart.service
> set 01 12:06:15 miria systemd[1]: Started Quectel EG25 autorestart timer.
> set 01 12:10:01 miria systemd[1]: eg25-autorestart.timer: Deactivated successfully.
> set 01 12:10:01 miria systemd[1]: Stopped Quectel EG25 autorestart timer.

It seems also to have restarted the working modem and froze phosh, but let's take it one step at a time.

**Comment by SantX27** [comment]
Even after a couple of reboots and re-enabling, the timer continues to die after firing once. The only thing I noticed is that now it waits for a multiple of 5 in minutes before firing. I might try to debug this seriously when I have a bit of time.

**Comment by kescherCode** [comment]
Odd, this is not the behaviour I saw. Reopening this issue.

**Comment by SantX27** [comment]
It turns out that I've modified eg25-autorestart.timer without realizing, and systemd kept using the old version despite updating. My fault, I should've doublechecked that. A `systemd revert eg25-autorestart.timer` fixed it, so I can finally close this issue. Thank you very much for helping!
